#Create the Export policy rule
- name: Create the export policy rules
  na_ontap_export_policy_rule: 
    state: present 
    vserver: "{{infrastructure_svm}}" 
    policy_name: default 
    client_match: "{{client_match}}" 
    protocol: "{{data_protocol}}" 
    ro_rule: sys 
    rw_rule: sys 
    super_user_security: sys 
    allow_suid: False 
    hostname: "{{inventory_hostname}}" 
    username: "{{username}}" 
    password: "{{password}}"
    https: true 
    validate_certs: false
  tags:
    - ontap_export_policy_rule
# Add the default export policy to the root volume
#- name: Add the default export policy to the root volume
#  na_ontap_volume: hostname="{{inventory_hostname}}" username="{{username}}" password="{{password}}" state=present name=rootvol policy=default vserver="{{infrastructure_svm}}" https=true validate_certs=false

# Create FlexVols for datastores
- name: Create FlexVols for datastores
  na_ontap_volume: 
    state: present 
    vserver: "{{infrastructure_svm}}" 
    policy: default 
    name: "{{item.0.name}}" 
    aggregate_name: "{{item.1.aggr_name}}" 
    size: "{{item.0.size}}" 
    is_online: True 
    space_guarantee: none 
    percent_snapshot_space: 0 
    junction_path: /{{item.0.name}} 
    hostname: "{{inventory_hostname}}" 
    username: "{{username}}" 
    password: "{{password}}"
    https: true 
    validate_certs: false
  with_together:
    - "{{datastores}}"
    - "{{data_aggregates}}"
  tags:
    - ontap_flexvol_datastore

# Create a FlexVol for the boot LUNs of servers
- name: Create a FlexVol for the boot LUNs of servers
  na_ontap_volume: 
    state: present 
    vserver: "{{infrastructure_svm}}" 
    policy: default 
    name: "{{boot_volume[0].name}}" 
    aggregate_name: "{{data_aggregates[0].aggr_name}}" 
    size: "{{boot_volume[0].size}}" 
    space_guarantee: none 
    percent_snapshot_space: 0 
    hostname: "{{inventory_hostname}}" 
    username: "{{username}}" 
    password: "{{password}}"
    https: true 
    validate_certs: false
  tags:
    - ontap_flexvol_boot_luns
