---
- name: Configure ONTAP for FlexPod
  hosts: ontap
  gather_facts: False
  vars_files: 
    - vars/ontap_main.yml
    - vars/common.yml
  connection: local
  roles:
  - { role: ONTAP/ontap_primary_setup, tags: [ 'ontap_primary_setup' ] }
  - { role: ONTAP/ontap_network, tags: [ 'ontap_network' ] }
  - { role: ONTAP/ontap_svm, tags: [ 'ontap_svm' ] }
  - { role: ONTAP/ontap_volumes, tags: [ 'ontap_volumes' ] }
  - { role: ONTAP/ontap_lifs, tags: [ 'ontap_lifs' ] }
  - { role: ONTAP/ontap_info, tags: [ 'ontap_info' ] }
  tags:
  - ontap_config
  - flexpod_config

- name: Configure ONTAP iGroups and LUNs
  hosts: ontap
  gather_facts: False
  vars_files:
    - vars/ontap_main.yml
    - vars/generated/ontap_lun_path
    - vars/generated/ontap_igroups
    - vars/common.yml
    - vars/generated/ucs_blades
    - vars/generated/ucs_sp_names
    - vars/generated/ucs_wwpn_a
    - vars/generated/ucs_wwpn_b
    - vars/generated/ucs_iqn
  vars:
    ontap_lun_path: "{{ lookup('file', 'vars/generated/ontap_lun_path') }}"
    ontap_igroups: "{{ lookup('file', 'vars/generated/ontap_igroups') }}"
    ucs_blades: "{{ lookup('file', 'vars/generated/ucs_blades') }}"
    ucs_sp_names: "{{ lookup('file', 'vars/generated/ucs_sp_names') }}"
    ucs_iqn: "{{ lookup('file', 'vars/generated/ucs_iqn') }}"
    ucs_wwpn_a: "{{ lookup('file', 'vars/generated/ucs_wwpn_a') }}"
    ucs_wwpn_b: "{{ lookup('file', 'vars/generated/ucs_wwpn_b') }}"
  connection: local
  roles:
  - { role: ci-ontap-roles/ontap_luns, tags: [ 'ontap_luns' ] }
  tags:
  - ontap_luns
  - flexpod_config 

