---
# Variables for Admin configurations of UCSM
# Un-comment the variables and set appropriate values to configure various
# parameters. If a variable is commented out, the script will skip configuration
# for that variable.

# Uncomment and update the the following lines to setup DNS Server(s)
dns_servers:
  - ip_address: "10.1.156.250"
  - ip_address: "10.1.156.251"

# Uncomment and update the the following line to setup Timezone
time_zone: 'America/New_York'
